<div id="pageLoader" class="pageLoader">
  Please wait...<br><br>
</div>

<div class="logo-container">
  <a href="www.villagetelco.org">  <!-- Set the URL link for the logo -->
    <img class="logoImage" src="/static/img/logo.png">
  </a>
</div>

<div class="topnav" id="docTopnav">

  <div></div> <!-- Space for the logo -->
  
	<a href="/cgi-bin/system-overview.has">System Overview</a>

	<a href="/cgi-bin/system-general.has">General</a>
 
	<div class="dropdown"> <!-- Library -->
   <button class="dropbtn"><strong>Library</strong></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/library-add.has">Add/Delete</a>
      <a href="/cgi-bin/library-copy.has">Copy</a>
      <!-- <a href="/cgi-bin/library-dup.has">Duplicate</a> -->
      <a href="/index.html">Home Page</a>
    </div>
  </div> 
 
	<a href="/cgi-bin/system-network.has">Network</a>

	<a href="/cgi-bin/system-wifi.has">WiFi</a>

	<a href="/cgi-bin/system-status.has">Network Status</a>

	<a href="/cgi-bin/system-firmware.has">Firmware Upgrade</a>

  <a href="/cgi-bin/logout.has">Logout</a>

  <div id="refreshIndicate" style="display: none;">AUTO<br>REFRESH</div>

  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="toggleNavbar()">&#9776;</a>
  
</div>

