<div id="pageLoader" class="pageLoader">
  Please wait...<br><br>
</div>

<div class="logo-container">
  <a href="www.villagetelco.org">  <!-- Set the URL link for the logo -->
    <img class="logoImage" src="/static/img/logo.png">
  </a>
</div>

<div class="topnav" id="docTopnav">

  <div></div> <!-- Space for the logo -->
  
	<a href="/cgi-bin/system-overview.cgi">System Overview</a>

	<div class="dropdown"> <!-- Library -->
   <button class="dropbtn"><strong>Library</strong></button>
    <div class="dropdown-content">
      <a href="/cgi-bin/library-add.cgi">Add/Delete</a>
      <a href="/cgi-bin/library-copy.cgi">Copy</a>
      <!-- <a href="/cgi-bin/library-dup.cgi">Duplicate</a> -->
      <a href="/index.html">Home Page</a>
    </div>
  </div> 
 
	<a href="/cgi-bin/system-general.cgi">General</a>
 
	<a href="/cgi-bin/system-wifi.cgi">WiFi</a>

	<a href="/cgi-bin/system-network.cgi">Network</a>

	<a href="/cgi-bin/system-status.cgi">Network Status</a>

	<a href="/cgi-bin/system-firmware.cgi">Firmware Upgrade</a>

  <a href="/cgi-bin/logout.cgi">Logout</a>

  <div id="refreshIndicate" style="display: none;">AUTO<br>REFRESH</div>

  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="toggleNavbar()">&#9776;</a>
  
</div>

