#!/bin/sh

# Set up Fallback IP for single Ethernet port
sleep 5  # make sure bridge is up

wanport=$(uci -q get board.eth.wanport)
select_wan=$(uci -q get diglib.wan.select_wan)

if [ $select_wan == "ethwan" ]; then
	# Fallback IP on wan for single Eth port 
	ifconfig $wanport:9 172.31.255.254 netmask 255.255.255.252
else
	# Fallback IP on br-lan if Ethernet WAN is not enabled
	ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
fi


