		<option value="1">1 2G</option>		<option value="6">6 2G</option>		<option value="11">11 2G</option>
		<option value="36">36</option>		<option value="38">38</option>		<option value="40">40</option>
		<option value="42">42</option>		<option value="44">44</option>		<option value="46">46</option>
		<option value="48">48</option>
		<option value="149">149</option>	<option value="151">151</option>	<option value="153">153</option>	
		<option value="155">155</option>	<option value="157">157</option>	<option value="159">159</option>
		<option value="161">161</option>	<option value="165">165</option>	

