#!/bin/sh /etc/rc.common
START=99

# /bin/config_cache.sh


start()
{	
# Set up Proxy configs

OCTET123="$(uci get network.lan.ipaddr | cut -d = -f 2 | cut -d . -f 1,2,3)"

CACHE_ENABLE=$(uci -q get cache.setup.cache_enable)

# Adjust IP settings
uci delete tinyproxy.tinyproxy.Allow
uci add_list tinyproxy.tinyproxy.Allow=$OCTET123".0/24"
uci add_list tinyproxy.tinyproxy.Allow=172.31.255.253  #Fallback client IP

uci delete polipo.general.allowedClients
uci add_list polipo.general.allowedClients=$OCTET123".0/24"
uci add_list polipo.general.allowedClients=172.31.255.253  #Fallback client IP

uci commit polipo
uci commit tinyproxy

# Enable cache
if [ $CACHE_ENABLE = "checked" ]; then
	/etc/init.d/tinyproxy enable
	/etc/init.d/polipo enable
	/etc/init.d/tinyproxy start
	/etc/init.d/polipo start
else	
	/etc/init.d/tinyproxy disable
	/etc/init.d/polipo disable
	/etc/init.d/tinyproxy stop
	/etc/init.d/polipo stop
fi

# Firewall proxy settings are in /etc/firewall.user

# Purge the on-disk cache at startup
sleep 1
polipo -c /tmp/etc/polipo.conf -x

}


