#!/bin/sh

# Default set up Fallback IP
sleep 5  # make sure bridge is up
ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252

# Make sure DHCP is updated
/etc/init.d/dnsmasq restart

# Make sure wifi is started
wifi


