#!/bin/sh /etc/rc.common
START=99

start()
{	
	# Check that wifi has started correctly
	wifi_check=$(iw dev | grep -c "channel")
	if [ $wifi_check == "0" ]; then
		wifi
		/etc/init.d/network restart
		/etc/init.d/dnsmasq restart
}
