#!/bin/sh /etc/rc.common
START=99

start()
{	
	# Check that wifi has started correctly
	wifi_check0=$(iwinfo | grep wlan0 -A 2 | grep -c -i "Channel")
	wifi_check1=$(iwinfo | grep wlan1 -A 2 | grep -c -i "Channel")
	if [ $wifi_check0 == "0" ] || [ $wifi_check1 == "0" ]; then
		wifi
		/etc/init.d/network restart
		/etc/init.d/dnsmasq restart
}
